pipeline {
    agent {
    docker {
        image 'maven:3.9.0'
        args '-v /root/.m2:/root/.m2' // You can remove this line if not needed
        volumes {
            hostPath('/root/.m2') // Mount host volume to container
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}